#! /bin/bash

ECLIPSE_WSPACE=""
DIR="$HOME/Workspace/"

if [ -n "$1" ]
then ECLIPSE_WSPACE=$DIR$1 
fi

echo eclipse workspace is $ECLIPSE_WSPACE

#exit $?
#$UBUNTU_MENUPROXY=0
setterm -fore green -reverse on
UBUNTU_MENUPROXY=0 eclipse-latest -data $ECLIPSE_WSPACE -name "$1" -clean

#exit $?
