#!/bin/sh
# used some from advanced script to have multiple ports: use an equal 
# number of guest and host ports

Guest_name=os12
Guest_ipaddr=10.0.0.99
Host_port=( '80' '8080' )
Guest_port=( '80' '8080' )
length=$(( ${#Host_port[@]} - 1 ))
if [ "${1}" = "${Guest_name}" ]; then
	if [ "${2}" = "stopped" -o "${2}" = "reconnect" ]; then
		for i in 'seq 0 $length'; do
			iptables -t nat -D PREROUTING -p tcp --dport ${Host_port[$i]} -j DNAT \
				--to ${Guest_ipaddr}:${Guest_port[$i]}
			iptables -D FORWARD -d ${Guest_ipaddr}/32 -p tcp -m state --state NEW \
				-m tcp --dport ${Guest_port[$i]} -j ACCEPT
		done
	fi
	if [ "${2}" = "start" -o "${2}" = "reconnect" ]; then
		for i in 'seq 0 $length'; do
			iptables -t nat -A PREROUTING -p tcp --dport ${Host_port[$i]} -j DNAT \
				--to ${Guest_ipaddr}:${Guest_port[$i]}
			iptables -I FORWARD -d ${Guest_ipaddr}/32 -p tcp -m state --state NEW \
				-m tcp --dport ${Guest_port[$i]} -j ACCEPT
		done
	fi
fi
